AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Moodle on AWS - Creates IAM roles and Instance profile

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Secrets Manager
        Parameters:
          - SecretArn
    ParameterLabels:
      SecretArn:
        default: Secrets Manager ARN

Parameters:
  SecretArn:
    Description: The Secrets Manger store ARN for BigBlueButton Secrets
    Type: String

Resources:
  InstanceRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: AssociateAddress api does not allow ARN other than *
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com.cn
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: metrics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource:
                  - '*'
                Condition:
                  StringEquals:
                    "cloudwatch:namespace": "BigBlueButton"
        - PolicyName: logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:*:*:*
        - PolicyName: AssociateEIP
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AssociateAddress
                Resource:
                  - '*'
        - PolicyName: SecretsManager
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:UpdateSecret
                Resource:
                  - !Ref SecretArn
        - PolicyName: ECRImages
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                Resource:
                  - '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref InstanceRole

Outputs:
  InstanceRole:
    Description: The IAM role of instance
    Value: !Ref InstanceRole
  InstanceProfile:
    Description: The instance profile
    Value: !Ref InstanceProfile

