AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host BigBlueButton on AWS - Creates App Server

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: App Server Parameter
        Parameters:
          - InstanceType
          - DomainName
          - DiskSize
          - SecretId
          - Email
          - EC2KeyName
          - SecurityGroup
          - Subnet
          - TurnServerEndpoint
          - EIPAllocationId
          - InstanceProfile
          - GreenlightAccountName
          - GreenlightAccountEmail
          - GreenlightAccountPassword
    ParameterLabels:
      InstanceType:
        default: App Server Instance Type
      DomainName:
        default: Domain Name
      DiskSize:
        default: Disk Size (GiB)
      SecretId:
        default: Secret Id
      Email:
        default: Email
      EC2KeyName:
        default: EC2 Key Name
      SecurityGroup:
        default: Security Group
      Subnet:
        default: Subnet
      TurnServerEndpoint:
        default: Turn Server Endpoint
      EIPAllocationId:
        default: EIP Allocation ID
      InstanceProfile:
        default: Instance Profile
      GreenlightAccountName:
        default: Account Name
      GreenlightAccountEmail:
        default: Email
      GreenlightAccountPassword:
        default: Password

Parameters:
  InstanceType:
    Description: Choose an instance type of App server
    AllowedValues:
      - t3.xlarge
      - t3.2xlarge
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: c5.2xlarge
    Type: String
  DomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: The domain of the App server
    Type: String
  DiskSize:
    Description: The Disk size
    Type: Number
    Default: 100
  SecretId:
    Description: The Secret Id to access from BigBlueButton Server
    Type: String
    Default: "12345678"
  Email:
    Description: Email for Let's encrypt to generate SSL Certificate
    Type: String
    AllowedPattern: \w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}
  EC2KeyName:
    Description: Name of an existing EC2 key pair
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroup:
    Description: Select the security group for App server
    Type: AWS::EC2::SecurityGroup::Id
  Subnet:
    Description: Select existing subnet.
    Type: AWS::EC2::Subnet::Id
  TurnServerEndpoint:
    Description: The endpoint address of Turn server
    Type: String
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
  EIPAllocationId:
    Description: The Allocation Id of EIP
    Type: String
    AllowedPattern: ^eipalloc-[0-9a-z]*
  InstanceProfile:
    Description: Instance profile name
    Type: String
  GreenlightAccountName:
    Description: Input the Admin user name
    Type: String
    Default: Admin
  GreenlightAccountEmail:
    Description: Account email for the admin user
    Type: String
    AllowedPattern: \w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}
  GreenlightAccountPassword:
    Description: Password for the admin user
    Type: String
    NoEcho: true

Mappings:
  RegionMap:
    cn-north-1:
      LatestAmiId: "ami-05bf8d3ead843c270"
    cn-northwest-1:
      LatestAmiId: "ami-09081e8e3d61f4b9e"

Resources:
  Logs:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      RetentionInDays: 7

  Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          server_init:
            - install-fonts
        install-fonts:
          packages:
            apt:
              fonts-arphic-uming: []
              fonts-wqy-zenhei: []
              fonts-cns11643-kai: []
              fonts-cns11643-sung: []
              fonts-moe-standard-kai: []
              fonts-moe-standard-song: []
              fonts-arphic-bkai00mp: []
              fonts-arphic-bsmi00lp: []
              fonts-arphic-ukai: []
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT120M
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref DiskSize
            VolumeType: gp2
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", LatestAmiId]
      KeyName: !Ref EC2KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref Subnet
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            # Update timezone
            rm -f /etc/localtime
            ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

            # 0. Replace with Tuna Ubuntu 16.04 apt source
            mv /etc/apt/sources.list /etc/apt/sources.list.bak
            cat >> /etc/apt/sources.list << EOL
            deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
            deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
            deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
            # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
            deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
            # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
            deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
            # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse

            deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
            # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
            EOL
            chmod 644 /etc/apt/sources.list
            apt-get update -y

            # 1. CloudWatch Agent
            wget -O /tmp/amazon-cloudwatch-agent.deb https://s3.${AWS::Region}.${AWS::URLSuffix}/amazoncloudwatch-agent-${AWS::Region}/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
            dpkg -i -E /tmp/amazon-cloudwatch-agent.deb
            cat >> /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << EOL
            {
            "agent": {
            "metrics_collection_interval": 60,
            "region": "${AWS::Region}",
            "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
            "debug": false,
            "run_as_user": "cwagent"
            },
            "metrics": {
            "namespace": "BigBlueButton",
            "append_dimensions": {
              "InstanceId": "\${!aws:InstanceId}"
            },
            "metrics_collected": {
              "disk": {
                "resources": ["/"],
                "measurement": [
                  { "name": "free", "unit": "Gigabytes" },
                  { "name": "total", "unit": "Gigabytes"},
                  { "name": "used", "unit": "Gigabytes"}
                ],
                "ignore_file_system_types": [
                  "sysfs", "devtmpfs"
                ],
                "metrics_collection_interval": 60
              }
            }
            },
            "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/var/log/cloud-init-output.log",
                    "log_group_name": "${Logs}",
                    "log_stream_name": "{instance_id}/cloud-init-output.log"
                  },
                  {
                    "file_path": "/var/log/cloud-init.log",
                    "log_group_name": "${Logs}",
                    "log_stream_name": "{instance_id}/cloud-init.log"
                  },
                  {
                    "file_path": "/var/log/nginx/bigbluebutton.access.log",
                    "log_group_name": "${Logs}",
                    "log_stream_name": "{instance_id}/nginx-access.log"
                  },
                  {
                    "file_path": "/var/log/nginx/error.log",
                    "log_group_name": "${Logs}",
                    "log_stream_name": "{instance_id}/nginx-error.log"
                  },
                  {
                    "file_path": "/var/log/bigbluebutton",
                    "log_group_name": "${Logs}",
                    "log_stream_name": "{instance_id}/tomcat-bigbluebutton.log"
                  }
                ]
              }
            },
            "log_stream_name": "{instance_id}"
            }
            }
            EOL
            chmod 444 /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
            sleep 5

            # 2. Install AWS CLI and associcate EIP
            apt-get install awscli -y
            instanceId=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
            aws ec2 associate-address --allocation-id ${EIPAllocationId} --instance-id $instanceId --region ${AWS::Region}
            sleep 5

            # 3. Install CloudFormation helper scripts and Fonts
            apt-get install -y python-pip
            pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
            pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
            wget -O /tmp/aws-cfn-bootstrap-latest.tar.gz https://aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            pip install /tmp/aws-cfn-bootstrap-latest.tar.gz
            /usr/local/bin/cfn-init --configsets server_init --verbose --stack ${AWS::StackName} --resource Instance --region ${AWS::Region}

            # 4. Use Tuna RubyGems Mirror
            apt-get install ruby -y
            gem sources --add https://mirrors.tuna.tsinghua.edu.cn/rubygems/ --remove https://rubygems.org/
            apt-get install ruby-bundler -y
            bundle config mirror.https://rubygems.org https://mirrors.tuna.tsinghua.edu.cn/rubygems

            # 5. Change PPA Source: yq, bigbluebutton-support, certbot
            cat >> /etc/apt/sources.list.d/rmescandon-ubuntu-yq-xenial.list << EOL
            deb [trusted=yes] http://aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn/ppa/rmescandon/yq/ubuntu xenial main
            EOL
            cat >> /etc/apt/sources.list.d/bigbluebutton-ubuntu-support-xenial.list << EOL
            deb [trusted=yes] http://aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn/ppa/bigbluebutton/support/ubuntu xenial main
            EOL
            cat >> /etc/apt/sources.list.d/certbot-ubuntu-certbot-xenial.list << EOL
            deb [trusted=yes] http://aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn/ppa/certbot/certbot/ubuntu xenial main
            EOL

            # 6. docker-ce Tuna Mirror
            apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
            apt-get update -y

            # 7. Download bbb-install.sh and modify the content
            cd /tmp/
            git clone https://github.com/JoeShi/bbb-install.git --depth 1
            cd ./bbb-install
            sed -i 's/PACKAGE_REPOSITORY=ubuntu.bigbluebutton.org/PACKAGE_REPOSITORY=aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn\/ppa\/bigbluebutton/' /tmp/bbb-install/bbb-install.sh
            sed -i 's/deb https:\/\/$PACKAGE_REPOSITORY\/$VERSION bigbluebutton-$DISTRO main/deb [trusted=yes] https:\/\/$PACKAGE_REPOSITORY\/$VERSION bigbluebutton-$DISTRO main/' /tmp/bbb-install/bbb-install.sh
            sed -i 's/download.docker.com\/linux\/ubuntu/mirrors.tuna.tsinghua.edu.cn\/docker-ce\/linux\/ubuntu/g' /tmp/bbb-install/bbb-install.sh
            sed -i 's/https:\/\/github.com\/docker\/compose\/releases\/download/https:\/\/get.daocloud.io\/docker\/compose\/releases\/download/' /tmp/bbb-install/bbb-install.sh
            # Change MongoDB Source
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
            sed -i 's/deb http:\/\/repo.mongodb.org\/apt\/ubuntu/deb [trusted=yes] https:\/\/mirrors.tuna.tsinghua.edu.cn\/mongodb\/apt\/ubuntu/' /tmp/bbb-install/bbb-install.sh
            # to avoid DNS lookup issue
            sed -i 's/nc -zvw3 $external_ip 443/nc -zvw10 $external_ip 443/' /tmp/bbb-install/bbb-install.sh
            chmod 500 /tmp/bbb-install/bbb-install.sh

            # 8. Install BigBlueButton App Server
            /tmp/bbb-install/bbb-install.sh -s ${DomainName} -v xenial-220 -c ${TurnServerEndpoint}:${SecretId} -e ${Email} -g

            # 9. Create Greenlight Admin user
            docker exec greenlight-v2 bundle exec rake user:create["${GreenlightAccountName}","${GreenlightAccountEmail}","${GreenlightAccountPassword}","admin"]

            # 10. Signal CloudFormation EC2 create completed with status code
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Instance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

Outputs:
  AppServerEndpoint:
    Description: App Server Endpoint
    Value: !Ref DomainName
