AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host BigBlueButton on AWS - Creates Turn Server

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Turn Server Parameter
        Parameters:
          - InstanceType
          - DomainName
          - DiskSize
          - SecretId
          - Email
          - EC2KeyName
          - SecurityGroup
          - Subnet
          - EIPAllocationId
          - InstanceProfile
    ParameterLabels:
      InstanceType:
        default: Turn Server Instance Type
      DomainName:
        default: Domain Name
      DiskSize:
        default: Disk Size (GiB)
      SecretId:
        default: Secret Id
      Email:
        default: Email
      EC2KeyName:
        default: EC2 Key Name
      SecurityGroup:
        default: Security Group
      Subnet:
        default: Subnet
      EIPAllocationId:
        default: EIP Allocation ID
      InstanceProfile:
        default: Instance Profile

Parameters:
  InstanceType:
    Description: Choose an instance type of Turn server
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: c5.large
    Type: String
  DomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: The domain of the Turn server
    Type: String
  DiskSize:
    Description: The Disk size
    Type: Number
    Default: 100
  SecretId:
    Description: The Secret Id to access from BigBlueButton Server
    Type: String
  Email:
    Description: Email for Let's encrypt to generate SSL Certificate
    Type: String
    AllowedPattern: \w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}
  EC2KeyName:
    Description: Name of an existing EC2 key pair
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroup:
    Description: Select the security group for Turn server
    Type: AWS::EC2::SecurityGroup::Id
  Subnet:
    Description: Select existing subnet.
    Type: AWS::EC2::Subnet::Id
  EIPAllocationId:
    Description: The Allocation Id of EIP
    Type: String
    AllowedPattern: ^eipalloc-[0-9a-z]*
  InstanceProfile:
    Description: Instance profile name
    Type: String

Mappings:
  RegionMap:
    cn-north-1:
      LatestAmiId: "ami-01993b4213b4bffb5"
    cn-northwest-1:
      LatestAmiId: "ami-01d4e30d4d4952d0f"

Resources:

  Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          server_init:
            - download-bbb-install
        download-bbb-install:
          packages:
            apt:
              git: []
          commands:
            download-bbb-install:
              command:
                - git clone https://github.com/bigbluebutton/bbb-install.git --depth 1
                - cd ./bbb-install
                - sed -i 's/PACKAGE_REPOSITORY=ubuntu.bigbluebutton.org/PACKAGE_REPOSITORY=aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn\/bigbluebutton/' /tmp/bbb-install/bbb-install.sh
                - sed -i 's/download.docker.com\/linux\/ubuntu\//mirrors.tuna.tsinghua.edu.cn\/docker-ce\/linux\/ubuntu\//' /tmp/bbb-install/bbb-install.sh
                - chmod 500 /tmp/bbb-install/bbb-install.sh
              cwd: /tmp
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT30M
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref DiskSize
            VolumeType: gp2
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", LatestAmiId]
      KeyName: !Ref EC2KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref Subnet
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            apt-get update -y
            # Install AWS CLI and associcate EIP
            apt-get install awscli -y
            instanceId=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
            aws ec2 associate-address --allocation-id ${EIPAllocationId} --instance-id $instanceId --region ${AWS::Region}
            apt-get install -y python-pip
            # Install CloudFormation helper scripts
            wget -O /tmp/aws-cfn-bootstrap-latest.tar.gz https://aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            pip install /tmp/aws-cfn-bootstrap-latest.tar.gz
            # Download bbb-install.sh
            cd /tmp/
            git clone https://github.com/bigbluebutton/bbb-install.git --depth 1
            cd ./bbb-install
            sed -i 's/PACKAGE_REPOSITORY=ubuntu.bigbluebutton.org/PACKAGE_REPOSITORY=aws-solutions-assets.s3.cn-north-1.amazonaws.com.cn\/bigbluebutton/' /tmp/bbb-install/bbb-install.sh
            sed -i 's/download.docker.com\/linux\/ubuntu/mirrors.tuna.tsinghua.edu.cn\/docker-ce\/linux\/ubuntu/g' /tmp/bbb-install/bbb-install.sh
            chmod 500 /tmp/bbb-install/bbb-install.sh
            # Install Turn Server
            /tmp/bbb-install/bbb-install.sh -c ${DomainName}:${SecretId} -e ${Email}
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Instance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

Outputs:
  TurnServerEndpoint:
    Description: Turn Server Endpoint
    Value: !Ref DomainName

